### ISSUE TITLE
"Issueベースの開発" レビュー依頼

### ISSUE THREAD

**Issue by g-sawada** [g-sawada/u-on-zu#13]
## 概要
雨温図作成・管理アプリ U-ON-ZU! のIssue一覧です。

Project https://github.com/users/g-sawada/projects/1

README https://github.com/g-sawada/u-on-zu

<br>
<br>
<br>

## 実装予定の機能

**MVPリリース段階で実装したい機能**

- [ ] グラフ作成機能
- [ ] データ検索・呼び出し機能
- [ ] 画像保存機能
- [ ] 会員登録機能
- [ ] Google認証機能
- [ ] マイグラフ保存・管理機能
- [ ] マイテンプレート保存・管理機能
- [ ] 都市データ閲覧機能

**※ 本リリース段階で実装したい機能**

- [ ] データを世界各地の都市に対応
- [ ] 地図からデータを呼び出す機能
- [ ] 作成したグラフをX（Twitter）に投稿できる機能

### 必要なページ

- [ ] トップページ
- [ ] ログインページ
- [ ] パスワードリセット申請ページ
- [ ] パスワード再設定ページ
- [ ] マイページ
- [ ] メインページ（作図画面）
- [ ] マイグラフ一覧ページ
- [ ] マイグラフ詳細ページ
- [ ] マイテンプレート一覧ページ
- [ ] マイテンプレート編集ページ
- [ ] 都市データ一覧ページ
- [ ] 都市データ詳細ページ
- [ ] プライバシーポリシーページ
- [ ] 利用規約ページ
- [ ] 問い合わせページ

**Comment by tarakish** [comment]
確認しました。
各項目はIssue化し、Issueの説明欄には機能実装のために必要なタスクをチェックボックス形式で記載するようにしてください。

**Comment by g-sawada** [comment]
ご確認ありがとうございます。
Projectの方で上記のMVPリリースまでの機能をissue化しました。必要なタスクを記載しています。
各タスクはさらに細かく分け，ストーリーポイントを設定してDraft状態にしてあります。
再度ご確認をよろしくお願いいたします。

https://github.com/users/g-sawada/projects/1/views/1

**Comment by Tsuchiya2** [comment]
Todoのカードの中でストーリーポイントが振られていないものがあるのでご確認をお願いします。もしMVPでは取り組まないものでしたら、「MVP後」という列を作ってそちらにカードを移動してください。

**Comment by g-sawada** [comment]
ご確認ありがとうございます。

- ストーリーポイントを付与しました。タスクをまとめて記載しているカードにも、一応大きめの数値でポイントを割り振りました。
- 「MVP後」を追加しました。

お手数おかけしますが、今一度チェックをよろしくお願いいたします
https://github.com/users/g-sawada/projects/1/views/1

**Comment by tmtkzk0823** [comment]
ストーリーポイント5以上を付けているカードですが、初めて取り組むものや見通しが立っていないものにポイント5~を付けているように見受けられました。ストーリーポイント1,2,3になるまで細分化することで、分かっている箇所、不透明な箇所が可視化されますし、進捗を感じながら開発を進めることができます。

上記の観点を踏まえてもう一度ご確認をお願いします。

**Comment by g-sawada** [comment]
チェックをありがとうございます。
タスクを全て細分化し、見えている範囲は全てTodoにてissue化しました。各issueの工程もできるだけチェックリストの形で記載しています。
ストーリーポイントは全て3以内になっているはずです。

度々お手数おかけしますが、今一度ご確認のほどよろしくお願い致します。

https://github.com/users/g-sawada/projects/1/views/1

**Comment by kenchasonakai** [comment]
LGTMです！
