### ISSUE TITLE
MVPリリース用issue

### ISSUE THREAD

**Issue by g-sawada** [g-sawada/u-on-zu#145]
MVPリリース用のissueになります。ご確認よろしくお願いいたします。

## 各種情報
サービス名：　U-ON-ZU!
サービスURL ：　https://u-on-zu-a19eaa736c87.herokuapp.com/

## READMEレビュー時にMVPリリース時点で実装予定だった機能

- グラフ作成機能（データは日本国内の都市のみ）
- データ検索・呼び出し機能（検索バーのみ）
- 画像保存機能
- 会員登録機能
- Google認証機能
- マイグラフ保存・管理機能
- マイテンプレート保存・管理機能

### READMEレビュー時に実装予定だった機能が実装できているかがわかるように記載してください
- グラフ作成機能については，概ね実装できました。グラフ作成メイン画面で右ドロワーを展開し，ユーザーが自由にグラフをデザインすることができます。本リリースに向けて，グラフライブラリRechartsについてさらに詳しく研究し，操作できそうな項目があれば，追加したいと思います。

<img width="929" alt="スクリーンショット 2024-05-25 18 40 35" src="https://github.com/g-sawada/u-on-zu/assets/118000212/ebbc06be-1948-42d8-8841-58cda5f5a391">

<br />
<br />
<br />
<br />

- データ検索・呼び出し機能は，下ドロワーを展開し，任意の都市のデータを呼び出してグラフに反映させることができるようにしました。
- 画像をpng形式で出力できるようにしました。出力時に，ファイル名の指定とリサイズをできるようにしています。
- ユーザー登録機能は，Sorceryの基本認証で実装しました。
- ログインユーザーのみ，作成したグラフに名前やメモをつけて，マイグラフとして保存することができます。保存したグラフはマイグラフ一覧からみることができ，「編集」ボタンを押すと，保存済みのデータと共にメイン画面に遷移します。削除機能も実装しました。
- ログインユーザーのみ，グラフデザインのテンプレートを保存することができます。テンプレートの保存，呼び出しは右ドロワー内から行います。他のグラフを作成する際に，自分のテンプレートデザインを簡単に適用することが可能です。マイテンプレート一覧から作成したマイテンプレートを確認できます。削除機能も実装しました。
- これら，マイグラフ機能とマイテンプレート機能はログインユーザー限定機能とするため，グラフ作成メイン画面にて，ボタンをdisabledで描画し，マウスホバーでログイン限定機能であることを通知するデザインにしました。

## READMEレビュー時から変更した機能
開発途中でMVPリリース時点で作らなくなった機能や追加した機能があれば記載してください

- データ検索・呼び出し機能について，MVP時点ではモックデータ4都市のみとしました。JSONファイルを元にしたseedの作成方法は検証済みです。今後，気象庁のサイトからダウンロードしたcsvファイルを，スクリプトで効率的にJSONファイルにに変換し，一括読み込みさせる予定です
- Google認証は，優先度が高くないと考え，MVPリリースの要件から外しました。本リリースまでの実装とします。

<br />
<br />

### ユーザー登録→自動ログイン
https://drive.google.com/file/d/1clwHiilZzWqXbJ54Z11CnDiy13tOJUoH/view?usp=drive_link

<br />
<br />

### 都市データ呼び出し・反映の様子
https://i.gyazo.com/bdf3d8e3c422dcd803ded77fc080f4b8.gif

<br />
<br />

### 未ログイン状態のメイン画面で，マイグラフ・マイテンプレート機能がdisabledになっている様子
<img width="958" alt="スクリーンショット 2024-05-26 2 00 29" src="https://github.com/g-sawada/u-on-zu/assets/118000212/cd20df6d-55db-4c0a-967d-c5e34b46857e">

<br />
<br />

### 画像ファイルを出力する様子
https://i.gyazo.com/2f82e04c9fc5a4489cb9896c4d298221.gif

<br />
<br />

### マイグラフ登録　→　マイグラフ一覧から呼び出して再利用する様子
https://drive.google.com/file/d/1GtkmNMLxKj65KMpR-X8PIABu-SX1Dv0M/view?usp=drive_link

<br />
<br />

### マイテンプレート登録　→　他のグラフでマイテンプレートを呼び出して適用する様子
https://drive.google.com/file/d/1sXpdx65uW7nBXmI0nxHGUX4tC5KiS9dA/view?usp=sharing

**Comment by tmtkzk0823** [comment]
ご提出ありがとうございます。
機能の確認ができました。
LGTMです！

**Comment by g-sawada** [comment]
さっそくチェックいただきありがとうございました！
こちらはCloseさせていただきます。
